<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>CuraDDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>3</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c8fe9460-be5c-4da7-a918-d757242f94ae</testSuiteGuid>
   <testCaseLink>
      <guid>dd95c219-b090-4ab7-ad85-7dc82ce7bdee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CURA/Make Multiple Appointments</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>736eab27-ad5f-410f-8aa2-c7a8c72caacc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/MakeAppointmentDataCura</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>736eab27-ad5f-410f-8aa2-c7a8c72caacc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>facility</value>
         <variableId>86c3c872-2eda-48dc-8990-fdf3faba3f3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>736eab27-ad5f-410f-8aa2-c7a8c72caacc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>program</value>
         <variableId>ec16804a-e216-49d2-9ec9-0c11c9ddd447</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>736eab27-ad5f-410f-8aa2-c7a8c72caacc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>date</value>
         <variableId>3d53003e-9a7f-45f8-945c-c2cc76d0b714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>736eab27-ad5f-410f-8aa2-c7a8c72caacc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>comment</value>
         <variableId>89942019-df3a-48cd-a8f2-a2fbf691d524</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
