<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_AugmenterProvider</name>
   <tag></tag>
   <elementGuidId>b2eac61c-7227-43cf-8e1e-c757f2f27768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;interface in org.openqa.selenium.remote&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'AugmenterProvider')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98e5ea0e-dbf4-4e1c-9ca3-e4459ed8edd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../remote/AugmenterProvider.html</value>
      <webElementGuid>d38273a8-6e60-4e5f-86fa-5157a7ebeb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in org.openqa.selenium.remote</value>
      <webElementGuid>c13d9afb-b333-4d0c-97e9-19f66ba1d0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AugmenterProvider</value>
      <webElementGuid>667372f4-58a0-4eb4-bf42-558c7c5f2835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;description&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/dl[1]/dd[1]/code[1]/a[1]</value>
      <webElementGuid>cda79443-2967-4cb4-91a2-87bfc32294ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BiDiProvider/iframe_classFrame</value>
      <webElementGuid>174a445d-abda-45de-b2bc-a0089021a768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AugmenterProvider')]</value>
      <webElementGuid>f32cdf22-af6c-4c95-a195-8a47324c907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Implemented Interfaces:'])[1]/following::a[1]</value>
      <webElementGuid>6ea36c73-de5c-4ed6-a8ba-23f4e96486b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HasBiDi'])[1]/preceding::a[1]</value>
      <webElementGuid>b5ee65b0-5a22-4839-a1c0-d1551e4e7de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AugmenterProvider']/parent::*</value>
      <webElementGuid>4dede5e1-65fa-48e3-a8cc-5f8dbd96118c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../remote/AugmenterProvider.html')]</value>
      <webElementGuid>dbfa9f54-fa07-49ee-b5c5-5e00548d80c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//code/a</value>
      <webElementGuid>f4c7871f-768b-4a2d-8cc8-41ed9a551150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../remote/AugmenterProvider.html' and @title = 'interface in org.openqa.selenium.remote' and (text() = 'AugmenterProvider' or . = 'AugmenterProvider')]</value>
      <webElementGuid>275d30dd-2aec-431b-b57e-753fcc635835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
